### ISSUE TITLE
Search bar icon not centered with new Materialize version

### ISSUE THREAD

**Issue by udiboy1209** [udiboy1209/fast_playlist#16]
![screenshot-2017-11-20 david bowie - heroes](https://user-images.githubusercontent.com/7384411/33014230-a89afa30-ce0c-11e7-8d34-b2b7363625aa.png)

The search icon should be centered. There is some simple issue with the CSS used for the nav-bar which needs to be fixed. Ideal fix would be to use some appropriate `class` value for the `<label>` tag [here](https://github.com/udiboy1209/fast_playlist/blob/master/index.html#L27)

```html
<input id="search" type="search" autocomplete="off" placeholder="Search Youtube"></input>
<label for="search"><i class="material-icons">search</i></label>
```

**Comment by Jigar3** [comment]
I would like to work on this issue.
Actually when I am running localhost:8080, I am getting dns lookup falied error
I am connected to college network using proxy
Can you help me out here as I am new to opensource development

**Comment by udiboy1209** [comment]
@Jigar3 you can start with this basic issue. 

http://localhost:8080 is a self-served hostname i.e. it is present locally on your machine and no kind of internet connection is required to access it. You can try the ip directly : http://127.0.0.1:8080

Basic debugging pointers would be to check if the SimpleHTTPServer is running. `./server start` will notify you if it is already running. Also, what OS are you on? Most OSes (Debian based, Windows, OSX) would have `localhost` bound to `127.0.0.1`.
