### ISSUE TITLE
[Feature Request] Button to clear whole playlist

### ISSUE THREAD

**Issue by CodeMaxx** [udiboy1209/fast_playlist#2]
Currently you have to clear cache to start a new playlist. @udiboy1209

**Comment by chamow97** [comment]
Can I work on this issue? @udiboy1209

**Comment by udiboy1209** [comment]
@chamow97 look at #7 you can finish that PR with the changes I have suggested.

**Comment by chamow97** [comment]
Okay, I will look into it @udiboy1209
